language: node_js
node_js:
- 16.17.1
script:
- npm run build
- npm run test
before_install:
- openssl aes-256-cbc -K $encrypted_68a09d8de4e1_key -iv $encrypted_68a09d8de4e1_iv
  -in tokenGDrive.json.enc -out tokenGDrive.json -d
- openssl aes-256-cbc -K $encrypted_b63016c0da68_key -iv $encrypted_b63016c0da68_iv
  -in credentialsGDrive.json.enc -out credentialsGDrive.json -d
