'use strict';

import * as fs from 'fs';
import * as google from '@googleapis/drive';
import { OAuth2Client } from '@googleapis/drive/node_modules/google-auth-library';

import { Auth$UtilsGDrive } from '../index';
import { UtilsGDriveError } from './utilsGDriveError';

/**
 * Credentials for authenticating Google API clients.
 * Generated by Google.
 */
export interface Credentials$GoogleApi {
  installed: {
      client_secret: string,
      client_id: string,
      redirect_uris: string
  }
}

export function getOAuth2Client(credentials: Credentials$GoogleApi): OAuth2Client {
  const { client_secret, client_id, redirect_uris } = credentials.installed;
  const oAuth2Client = new google.auth.OAuth2(client_id, client_secret, redirect_uris[0]);
  return oAuth2Client;
}

export function resolveCredentials(auth: Auth$UtilsGDrive = {}): Credentials$GoogleApi {
    if (auth.credentials) { 
      if (typeof auth.credentials === 'string') return JSON.parse(auth.credentials);
      return auth.credentials;
    } else if (auth.pathCredentials) {
        return JSON.parse(fs.readFileSync(auth.pathCredentials).toString());
    } else {
      try {
        return JSON.parse(fs.readFileSync('credentialsGDrive.json').toString());
      } catch (err) {
        throw new UtilsGDriveError('Credentials not found.');
      }
    }
  }
  